addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.13")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.7.5")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"        % "0.15.0")
addSbtPlugin("com.github.gseitz"         % "sbt-release"         % "1.0.13")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.19")
